# Generated by Django 4.1.4 on 2023-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=80)),
                ('message', models.TextField()),
            ],
        ),
    ]
