# Generated by Django 4.1.4 on 2023-01-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactform',
        ),
    ]
