# Generated by Django 4.1.4 on 2023-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_image', models.FileField(default=None, max_length=255, null=True, upload_to='recipes/')),
                ('recipe_date', models.DateField()),
                ('recipe_title', models.CharField(max_length=50)),
                ('recipe_rating', models.IntegerField(verbose_name=5)),
                ('recipe_comment', models.CharField(max_length=50)),
            ],
        ),
    ]
