# Generated by Django 4.1.4 on 2023-01-04 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_cooktime',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_des',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_preparetime',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_readyin',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_servings',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_youtubelink',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 18, 22, 35, 904197, tzinfo=datetime.timezone.utc),blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_rating',
            field=models.SmallIntegerField(),
        ),
    ]
